dev:
	latexmk -xelatex -shell-escape -synctex=1 -interaction=errorstopmode -file-line-error -output-directory=./out -pvc -f main.tex

clean:
	rm ./out/*.aux ./out/*.log ./out/*.toc ./out/*.lof ./out/*.lot ./out/*.out ./out/*.synctex.gz ./out/*.synctex ./out/*.fls ./out/*.fdb_latexmk